mysite/common/urls.py
from django.urls.resolvers import URLPattern
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from pytest import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pytest/',include('pytest.urls')),
    path('common/',include('common.urls')),
    path('',views.index, name='index'),
]

mysite/pytest/urls.py
from django.urls import path

from . import views

#for app_name duplicate problem
app_name = 'pytest'

urlpatterns = [
    #path('',views.index),
    #path('<int:question_id>/',views.detail),

    #for url nicname
    path('',views.index,name='index'),
    path('<int:question_id>/',views.detail,name='detail'),
    path('answer/create/<int:question_id>/',views.answer_create, name='answer_create'),
    path('question/create/',views.question_create, name='question_create'),
]

mysite/common/models.py
from django.db import models

# Create your models here.

mysite/pytest/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

mysite/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label="E-mail")
    class Meta: 
        model = User
        fields = ("username", "passwor1","password2","email")

mysite/pytest/forms.py
from django import forms
from django.forms import widgets
from pytest.models import Question, Answer

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject','content']
        labels = {
            'subject':'제목',
            'content':'내용',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

mysite/common/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from common.forms import UserForm

# Create your views here.

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)

mysite/pytest/views.py
from django.shortcuts import render, get_object_or_404, redirect
#from django.http import HttpResponse
from django.utils import timezone
from .models import Question
from .forms import QuestionForm, AnswerForm
from django.core.paginator import Paginator


# Create your views here.

def index(request):
    #return HttpResponse("test")
    #input parameter
    page = request.GET.get('page','1')
    question_list = Question.objects.order_by('-create_date')
    #for paging
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)
    context = {'question_list':page_obj}
    #context = {'question_list': question_list}
    return render(request, 'pytest/question_list.html', context)

def detail(request,question_id):
    #question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pytest/question_detail.html', context)

def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)    
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pytest:detail', question_id=question.id)
    #answer = Answer(question=question, content=request.POST.get('content'),create_date=timezone.now())
    #question.answer_set.create(content = request.POST.get('content'),create_date=timezone.now())
    else:
        form = AnswerForm()
    context={'question':question, 'form':form}
    return render(request, 'pytest/question_detail.html',context)

def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question=form.save(commit=False)
            question.create_date = timezone.now()
            question.save()
            return redirect('pytest:index')
    else:
        form = QuestionForm()
    context = {'form':form}
    return render(request, 'pytest/question_form.html', context)

mysite/pytest/templates/pytest/question_list.html
{% if question_list %}
    <ul>
    {% for question in question_list %}
        <li>    
            <!--
                <a href="/pytest/{{ question.id }}/">{{ question.subject }}
                    <div><a href="/pytest/{{ question.id }}/">{{ question.content }}</a></div>
                    <br>
                </a>
            -->
            <!-- for url nicname -->
            <a href ="{% url 'pytest:detail' question.id %}">
                {{ question.subject}}
            </a>
        </li>
        <br>
    {% endfor %}
    </ul>
{% else %}
    <p>질문이 없습니다.</p>
{% endif %}

mysite/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-witdh, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <title> django tutorial! </title>
    </head>
    <body>
        {% include "navbar.html" %}
        <!-- template contents -->
        {% block content %} 
        {% endblock %}
        <!-- jQuery -->
        <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
        <!-- Bootstrap -->
        <script src="{% static 'bootstrap.min.js' %}"></script>
    </body>
</html>

mysite/templates/common/login.html
{% extends "base.html" %}
{% block content %}

<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>Login</h4>
        </div>
        <div class="col-8 text-right">
            <span>or <a href="{% url 'common:signup' %}">Register.</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username"> User ID </label>
            <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password"> Password </label>
            <input type="text" class="form-control" name="password" id="password" value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary"> Login! </button>
    </form>
</div>
{% endblock %}

mysite/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>
                    {{ field.label }}
                </strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>
                {{ error }}
            </strong>
        </div>
    {% endfor %}
{% endif %}

mysite/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'pytest:index' %}">Pytest</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}"> {{ user.username }} (로그아웃) </a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>

mysite/templates/pytest/question_detail.html
{% extends 'base.html' %}
{% block content %}

<!-- {% load static %} -->
<!-- link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}"-->

<div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'pytest:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

mysite/templates/pytest/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h4 class="my-3 border-bottom pb-2">게시글 작성</h4>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        <!-- error start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                    {% if field.errors %}
                    <strong> {{ field.label }}</strong>
                    {{ field.errors }}
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}
        <!-- error end -->
        <div class="form-group">
            <label for="subject"> title </label>
            <input type="text" class="form-control" name="subject" id="subject" value="{{ form.content.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content"> contents </label>
            <textarea class="form-control" name="content" id="content" rows="10">
                {{ form.content.value|default_if_none:'' }}
            </textarea>
        </div>
        <!-- {{ form.as_p}} -->
        <button type="submit" class="btn btn-primary"> 작성 </button>
    </form>
</div>
{% endblock %}

mysite/templates/pytest/question_list.html
{% extends 'base.html' %}
{% load pytest_filter %}
{% block content %}

<!-- {% load static %} -->
<!-- link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}" -->

<div class="container my-3">
    <table class="table">
        <thead>
            <tr class ="thead-dark">
                <th>번호</th>
                <th>제목</th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>
            {% if question_list %}
            {% for question in question_list %}
            <tr>
                <td>
                    {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
                </td>
                <td>
                    <a href ="{% url 'pytest:detail' question.id %}">
                    {{ question.subject}}
                    </a>
                    {% if question.answer_set.count > 0 %}
                    <span class="text-danger small ml-2">
                        {{ question.answer_set.count }}
                    </span>
                    {% endif %}
                </td>
                <td>{{question.create_date}}</td> 
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colsapn="3"> 질문이 없습니다.</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
        <!-- paging start -->
        <ul class="pagination justify-content-center">
            <!-- prev page -->
            {% if question_list.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
            {% endif %}
            <!-- list -->
            {% for page_number in question_list.paginator.page_range %}
            {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
                {% if page_number == question_list.number %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
                {% endif %}
            {% endif %}
            {% endfor %}
            <!-- next page -->
            {% if question_list.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
            {% endif %}
        </ul>
        <!-- paging end -->
    <a href="{% url 'pytest:question_create' %}" class="btn btn-primary"> 게시글 등록 </a>
</div>

{% endblock %}